### ISSUE TITLE
Questions of Appling AI models Across DBMSs

### ISSUE THREAD

**Issue by bajinsheng** [alibaba/pilotscope#1]
Hi, this project is quite interesting to me. Since this project provides a good abstraction layer between AI models and DBMSs, I am wondering whether it can train the same AI models across DBMSs, instead of training and predicting on a specific DBMS. For example, the MSCN algorithm is trained based on PostgreSQL in the example code. Can we use the dataset from multiple DBMSs to train the same MSCN model and directly apply it to different DBMSs?

Looking forward to your reply!

**Comment by duoyw** [comment]
Yes! Pilotscope utilizes the same pipeline to integrate AI models into DBMSs. However, Pilotscope currently only supports PostgreSQL and Spark. Development for additional DBMS compatibility is underway.
