### ISSUE TITLE
Questions of running test_lero_example.py

### ISSUE THREAD

**Issue by lucifer12346** [alibaba/pilotscope#3]
After changing self.config in function setup(), I run /test_example_algorithms/test_lero_example.py directly and here are some errors.
It seems an error of invalid device id is raised:
```
......
RelType :  {'Seq Scan', 'Bitmap Index Scan', 'Hash', 'Sort', 'Nested Loop', 'Materialize', 'Hash Join', 'Bitmap Heap Scan', 'Index Only Scan', 'Aggregate', 'Index Scan', 'Merge Join'}
Training data set size = 7055
input_feature_dim: 25
Invalid device id
Exception in thread pretraining_async_start:
......
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```
And after that here's another error:
```
start to test sql
current is the 0-th sql, and it is select count(*) from badges as b, users as u where b.userid= u.id and u.upvotes>=0
Terminate pilotscope either at the end of the program or in case of an exception.
E
======================================================================
ERROR: test_lero (__main__.LeroTest)

......

AttributeError: 'NoneType' object has no attribute 'transform'
```

I think if there is a standard output and if there are more configs I need to change since I installed my Postgresql in a different directory and use another user different from _pilotscope_.

**Comment by WoodyBryant** [comment]
It seems that you have the invalid device id.  You'd better check your device(the id of GPU) and modify the codes in algorithm_examples/Lero/source/model.py(the line 16, GPU_LIST).

**Comment by WoodyBryant** [comment]
Your GPU may be not the same as the original Lero codes. You can modify the GPU_LIST variable shown in the figure according to the number of your GPU device. For example, if you have just one GPU, you can modify the codes as 'GPU_LIST = [0]'.  The code is in 'algorithm_examples/Lero/source/model.py'
![issue](https://github.com/alibaba/pilotscope/assets/52766916/33b91a78-fe07-4969-9230-ca89917ccb5c)

**Comment by lucifer12346** [comment]
Thank you ! Now I can run the exmple code successfully!
